development:
  adapter: postgresql
  host: <%= ENV.fetch('ONAKA_DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('ONAKA_DB_PORT', 5432) %>
  username: <%= ENV.fetch('ONAKA_DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('ONAKA_DB_PASSWORD', '') %>
  database: 'onaka_development'

test:
  adapter: postgresql
  host: <%= ENV.fetch('ONAKA_DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('ONAKA_DB_PORT', 5432) %>
  username: <%= ENV.fetch('ONAKA_DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('ONAKA_DB_PASSWORD', '') %>
  database: 'onaka_test'

production:
  adapter: postgresql
  host: <%= ENV.fetch('ONAKA_DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('ONAKA_DB_PORT', 5432) %>
  username: <%= ENV.fetch('ONAKA_DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('ONAKA_DB_PASSWORD', '') %>
  database: 'onaka_production'
